TEST_MODE = False

import time
import requests
import redis
import pandas as pd
import logging
from utils.telegram_notifier import send_telegram

THRESHOLD = 2000  # PE-CE dead zone
UID="ITC2766"
HOST = "http://localhost:9000"
SQL_NIFTY = "select * from NiftyOISpikeNew latest on ts PARTITION by BatchId;"
REDIS_KEY = "NIFTY_OI_SIGNAL"

SQL_BANKNIFTY = "select * from BankNiftyOISpikeNew latest on ts PARTITION by BatchId;"
REDIS_KEY_BN = "BANKNIFTY_OI_SIGNAL"

CHECK_INTERVAL = 20  # seconds

r = redis.Redis(host="localhost", port=6379, decode_responses=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s"
)


def fetch_latest_pe_ce():
    resp = requests.get(
        f"{HOST}/exec",
        params={"query": SQL_NIFTY},
        timeout=2
    ).json()

    df = pd.DataFrame.from_dict(resp["dataset"])
    if df.empty:
        return None

    # df[8] = PE-CE (as per reference file)
    return float(df.iloc[-1][8])

def fetch_latest_pe_ce_banknifty():
    resp = requests.get(
        f"{HOST}/exec",
        params={"query": SQL_BANKNIFTY},
        timeout=2
    ).json()

    df = pd.DataFrame.from_dict(resp["dataset"])
    if df.empty:
        return None

    return float(df.iloc[-1][8])


def sign(val: float) -> int:
    if val > 0:
        return 1
    if val < 0:
        return -1
    return 0


def main():
    logging.info("OI Signal Engine started (TEST MODE=%s)", TEST_MODE)

    while True:
        try:
            # ---- NIFTY ----
            if r.hget(UID, "OI_ENGINE_ENABLED") == "ON":
                pe_ce = fetch_latest_pe_ce()
                if pe_ce is not None:
                    # ---- THRESHOLD FILTER ----
                    if abs(pe_ce) < THRESHOLD:
                        logging.info(
                            "[FILTER] PE-CE %.2f inside threshold (%d) → ignoring",
                            pe_ce, THRESHOLD
                        )
                    else:
                        current_sign = sign(pe_ce)
                        prev_sign = r.get("NIFTY_PREV_PECE_SIGN")

                        logging.info(
                            "[CHECK] PE-CE=%.2f | current_sign=%s | prev_sign=%s",
                            pe_ce, current_sign, prev_sign
                        )

                        if prev_sign is not None:
                            prev_sign = int(prev_sign)

                            if current_sign != prev_sign and current_sign != 0:
                                signal = "BULLISH" if current_sign == 1 else "BEARISH"

                                if TEST_MODE:
                                    logging.info(
                                        "[TEST MODE] SIGNAL → %s (PE-CE=%.2f)",
                                        signal, pe_ce
                                    )
                                else:
                                    r.hset(
                                        REDIS_KEY,
                                        mapping={
                                            "signal": signal,
                                            "pe_ce": pe_ce,
                                            "ts": time.time(),
                                            "status": "NEW"
                                        }
                                    )

                                    # --- TELEGRAM NOTIFICATION (Best Effort) ---
                                    try:
                                        spot = r.get("NF_SPOT")
                                        msg = (
                                            "📊 <b>NIFTY OI Crossover Detected</b>\n\n"
                                            f"Direction : <b>{signal}</b>\n"
                                            f"PE-CE     : <b>{pe_ce}</b>\n"
                                            f"NIFTY Spot: <b>{spot}</b>\n\n"
                                            "⏱ Signal generated by OI engine"
                                        )
                                        send_telegram(msg)
                                        logging.info("Telegram notification sent")
                                    except Exception as tg_err:
                                        logging.error(f"Telegram notification failed: {tg_err}")

                        # always update last seen sign
                        r.set("NIFTY_PREV_PECE_SIGN", current_sign)

        except Exception as e:
            logging.exception("Engine error")

        time.sleep(CHECK_INTERVAL)

        # -------------------------------
        # BANKNIFTY OI SIGNAL
        # -------------------------------
        if r.hget(UID, "BN_OI_ENGINE_ENABLED") == "ON":
            pe_ce_bn = fetch_latest_pe_ce_banknifty()
            if pe_ce_bn is None:
                pass

            elif abs(pe_ce_bn) < THRESHOLD:
                pass
            else: 
                current_sign_bn = sign(pe_ce_bn)
                prev_sign_bn = r.get("BANKNIFTY_PREV_PECE_SIGN")

                if prev_sign_bn is not None:
                    prev_sign_bn = int(prev_sign_bn)

                    if current_sign_bn != prev_sign_bn and current_sign_bn != 0:
                        signal_bn = "BULLISH" if current_sign_bn == 1 else "BEARISH"

                        if not TEST_MODE:
                            r.hset(
                                REDIS_KEY_BN,
                                mapping={
                                    "signal": signal_bn,
                                    "pe_ce": pe_ce_bn,
                                    "ts": time.time(),
                                    "status": "NEW"
                                }
                            )

                            try:
                                spot = r.get("BN_SPOT")
                                msg = (
                                    "📊 <b>BANKNIFTY OI Crossover Detected</b>\n\n"
                                    f"Direction : <b>{signal_bn}</b>\n"
                                    f"PE-CE     : <b>{pe_ce_bn}</b>\n"
                                    f"Spot      : <b>{spot}</b>"
                                )
                                send_telegram(msg)
                            except Exception:
                                pass

                r.set("BANKNIFTY_PREV_PECE_SIGN", current_sign_bn)


if __name__ == "__main__":
    main()
